# Generated by Django 4.1 on 2023-05-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(default='968646a2', max_length=8, unique=True),
        ),
    ]
