# Generated by Django 4.1 on 2023-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shortener', '0002_alter_shortenedurl_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='scheme',
            field=models.CharField(default='http', max_length=5),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(default='03f2417b', max_length=8, unique=True),
        ),
    ]
